sudo: required
dist: trusty
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: dC9my6rJX53JpT3kdjC6CC2kuq/pjeOl4bGG0VrnXGRvegvdQWxNV/RQzYPr67qyY2IAnGwdDGlYcFYV9q9c4v99nG+kuZlYtUPGzRWY2uDGmeaNwAIH3CMu3aWE5mHQ5jnQcybIYT+S09xuVm6pJ/1v6hugihB7y/z5Bb4zoA+O7968y3rCxa8leNUkFs5nDhq5tw6pjfIwwmT7WVCyXPb71WA65hq0/s6IfD4UqcPb9zu/mnPep/9mf0O5cGy46pZQi3+wxooStW9G+cjKm3aOuZ4mUiHbOAst6Yezljwo+1oNZbhodI2LYXhBaTzaFz9F7FjCHJzAeoPP+MCFium9+E872aiwjRqn7uiQM/eZICWYkVVPD2WYcuITG+OPnhtuq0CebXegQwXh5P3y1DBmTdaxsI1fnTqfAuPhv8tul6Y/NcMU51Q5MJBeaJqJf5UCHmeKPWyYWs9YgyISB3ygAhrcHeXno/iAK2flnR7lcnFMF5E7AxVjpcw3mEo6imWGogtV/rUPBcjgMJ93GJBSKhbq0vgpvcY6VB/tshIOH8OKkNh6ayiMuG37Bwm8Gt3A8QBeOZk263JGoGpvp00ExkIZmEKGxvDItDZxtBCIr4vHBSIJqHcdGtL89yYIKs6swYsLde5qaMxavkhmW9EW+VpmP7wnma7nvHLTF8Q=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: XyY9/m0VO+cA0hTKsxUusp20Ps/5I2Bec0P5Q/JDiulsWyU0cWPTyfvWCoutGM2x5Bg6RNXVP9gBGkTaab/7w0KZFe4HQYvda2W6wZsf00FTSqWwd6YyaJa0PctlGUUcTri1R7wmqWNSnQWgWO1Gvc4OPE7ps5t5bbxSpafkbPuEryEZ7w5somG8vUfO0Ck8RaH63GKPzH/mzKMJ+tRYrRkokjuafkwDQgeXBNsh5FQvPDtnfE2595PAZu9BnDsqs7LRo68CTevjWphZEFzs7r5fEnB+MyNt9xttHMl4z1jqje1Iexre99P7UHWvcNeNIfJlkFOBrPmNX9+bPCqjb+sZco5QDm3+BFxCdOzDcWqgjh0+91pA3YG0XtKqV9i1QFAvOnlU6PJla1j8wA2uhl5NkSGhzEQMxqvBK7CGJA4if3PdvxhdSt0fgORBWqFSD15pTnFKgYardyLueFiTn5ypLmcjamzN0C54z6hxhbYTo8JkWA+xJl6QeXfEyYcT75+u5dtu/BHbk/cKmKnBJDYKcEVP1CUSbgYwsgT83g1EoK2r7tV6KyUkIXuxu6sF4hNbE5Du4ky5E0Yp/jN4A6GeDQBXZonu5dI7kK6lZYTgGIdTLNn+wmp6p49FCNvFzbsb3+FkqniWuWMUT72v+qwlGV9G6CZIi/KrDY86K4Y=
